root = "."
tmp_dir = "tmp"

[build]
  bin = "./tmp/main"
  cmd = "templ generate && bun run build && go build -o ./tmp/main cmd/main.go"
  delay = 1800
  exclude_dir = ["tmp", "vendor", "node_modules", "devenv.nix"]
  exclude_file = []
  exclude_regex = [".*_templ.go", ".*/static/css/main.css", "templtodo.db", "templtodo.db.*", ".*/static/js/main.min.js"]
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "templ", "html", "css", "js"]
  kill_delay = "0s"
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = false
